name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint · Typecheck · Build (web)
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      BETTER_AUTH_SECRET: ci-only-dummy-secret
      WEB_ORIGIN: http://localhost:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies (workspace root)
        run: pnpm -w install --frozen-lockfile

      # Safety: ensure package-level node_modules links exist for web
      # Some runners mis-detect workspace links during turbo steps.
      - name: Install dependencies (web)
        run: pnpm -C apps/web install --frozen-lockfile

      - name: Lint
        run: pnpm -w turbo run lint

      - name: Typecheck
        run: pnpm -w turbo run typecheck

      - name: Build upstream emails (ensure subpath export types)
        run: pnpm -w turbo run build --filter=@repo/emails...

      - name: Build web app
        run: pnpm -w turbo run build --filter=web...